/**
 * FileEntryService — pure DB repository for the `file_entry` table.
 *
 * ## Scope
 *
 * - **Pure DB.** No FS IO, no path resolution, no canonicalization. Callers
 *   (e.g. `FileManager.ensureExternalEntry`) are responsible for passing a
 *   canonical `externalPath` on write and query.
 * - **Produces branded `FileEntry`.** Every returned row passes
 *   `FileEntrySchema.parse()` so the brand contract holds — downstream
 *   consumers cannot receive a raw object literal that satisfies the shape
 *   but bypasses validation.
 * - **No side effects beyond DB.** Dangling updates, watcher invalidation,
 *   and cache invalidation are orchestrated by FileManager — this service
 *   is strictly query/insert/update/delete.
 *
 * See [architecture.md](../../../docs/references/file/architecture.md) for the
 * module-level layering rules.
 */

import {
  and,
  asc,
  count,
  eq,
  gt,
  inArray,
  isNotNull,
  isNull,
  lt,
  notInArray,
  or,
  type SQL,
  sql,
  type SQLWrapper
} from 'drizzle-orm'
import { v7 as uuidv7 } from 'uuid'
import * as z from 'zod'
import { ZodError } from 'zod'

import { application } from '@application'
import { fileEntryTable } from '@data/db/schemas/file'
import { persistentRefAbsenceConditions } from '@data/db/schemas/fileRelations'
import type { DbOrTx } from '@data/db/types'
import { loggerService } from '@logger'
import { DataApiErrorFactory } from '@shared/data/api/errors'
import type { FileEntryListResponse, FileEntryStats } from '@shared/data/api/schemas/files'
import type {
  CleanupPolicy,
  ContentHash,
  FileEntry,
  FileEntryId,
  FileEntryOrigin,
  InternalFileEntry
} from '@shared/data/types/file'
import {
  CleanupPolicySchema,
  ContentHashSchema,
  ExternalEntrySchema,
  FileEntrySchema,
  InternalEntrySchema,
  SafeNameSchema
} from '@shared/data/types/file'
import type { FileType } from '@shared/types/file'
import { type CanonicalFilePath, fileTypeMap } from '@shared/utils/file'

import { asNumericKey, asStringKey, decodeListCursor, encodeCursor, keysetOrdering } from './utils/keysetCursor'

const logger = loggerService.withContext('FileEntryService')

// `cleanupPolicy` MUST stay required on both branches — no `.default()` / `.optional()`.
// This is the single compile-time forcing point that makes every creation surface
// choose a policy explicitly (file-entry-cleanup.md §4.1). Adding a default here would
// silently let a forgotten assignment fall through to the DB backstop, defeating the
// "leak recoverably rather than delete unrecoverably" invariant.
const CreateFileEntryRowSchema = z.discriminatedUnion('origin', [
  z.strictObject({
    id: InternalEntrySchema.shape.id,
    origin: z.literal('internal'),
    name: InternalEntrySchema.shape.name,
    ext: InternalEntrySchema.shape.ext,
    cleanupPolicy: CleanupPolicySchema,
    size: InternalEntrySchema.shape.size,
    contentHash: ContentHashSchema.nullable().optional()
  }),
  z.strictObject({
    origin: z.literal('external'),
    name: ExternalEntrySchema.shape.name,
    ext: ExternalEntrySchema.shape.ext,
    cleanupPolicy: CleanupPolicySchema,
    externalPath: ExternalEntrySchema.shape.externalPath
  })
])

/**
 * BO-shaped columns a caller may provide on insert. Internal callers provide
 * the id because the physical blob is already written at `{id}.{ext}`;
 * external ids are generated by `create()`. DB-row-only null columns are
 * derived here too.
 */
export type CreateFileEntryRow = z.input<typeof CreateFileEntryRowSchema>

/**
 * Columns that may be mutated through the generic update surface. Origin / id /
 * externalPath and bytes-derived metadata are intentionally excluded; content
 * commits use the dedicated begin / complete / restore methods below.
 */
export interface UpdateFileEntryRow {
  readonly name?: string
  readonly ext?: string | null
  readonly cleanupPolicy?: CleanupPolicy
  readonly deletedAt?: number | null
}

export interface InternalContentCommitSnapshot {
  readonly size: number
  readonly contentHash: ContentHash | null
  readonly updatedAt: number
  readonly commitAt: number
}

export interface FindEntriesQuery {
  readonly origin?: FileEntryOrigin
  readonly inTrash?: boolean
  readonly limit?: number
  readonly offset?: number
}

export type ListFilesSortBy = 'name' | 'createdAt' | 'updatedAt' | 'size' | 'ext'

export interface ListCursorQuery {
  readonly origin?: FileEntryOrigin
  readonly inTrash?: boolean
  readonly fileType?: FileType
  readonly sortBy?: ListFilesSortBy
  readonly sortOrder?: 'asc' | 'desc'
  readonly cursor?: string
  readonly limit?: number
}

export interface FileEntryService {
  /** Run serialized DB writes through DbService.withWriteTx (synchronous — no await needed). */
  withWriteTx<T>(fn: (tx: DbOrTx) => T): T

  /** Return the entry, or `null` if not found. Trashed entries are included. */
  findById(id: FileEntryId): FileEntry | null

  /** Tx-scoped variant of `findById` for composing write flows. */
  findByIdTx(tx: DbOrTx, id: FileEntryId): FileEntry | null

  /** Return the entry, or throw. Trashed entries are included. */
  getById(id: FileEntryId): FileEntry

  /** Tx-scoped variant of `getById` for composing write flows. */
  getByIdTx(tx: DbOrTx, id: FileEntryId): FileEntry

  /**
   * Look up an external entry by canonical `externalPath`. Returns `null` when
   * no row matches. The `CanonicalFilePath` brand forces callers through
   * `canonicalizeFilePath()` at compile time — raw `string` / bare `AbsoluteFilePath`
   * values are not assignable here, which prevents the "caller forgot to
   * canonicalize" class of bug that would silently miss all matches.
   */
  findByExternalPath(canonicalPath: CanonicalFilePath): FileEntry | null

  /**
   * Return external entries whose `externalPath` matches `canonicalPath`
   * case-insensitively (`lower(externalPath) = lower(canonicalPath)`).
   * Byte-exact matches are included; callers that only want "case-different
   * peers" should filter the byte-exact self-match from the result.
   *
   * Backed by the functional unique index `fe_external_path_lower_unique_idx`
   * (`lower(external_path)`) — SQLite expression-matches the WHERE clause
   * against the index, so this lookup is O(log N) and runs the same plan
   * regardless of `file_entry` table size. The size-threshold gate that the
   * earlier "best-effort warn-only" contract recommended is no longer needed
   * and has been removed from the architecture doc.
   *
   * Returns at most one row in practice: the same functional unique index
   * makes "two rows that case-collide" an unrepresentable DB state. The
   * array return shape is preserved for forward-compat with possible future
   * relaxations (e.g. a trashed-aware variant), and so call sites that
   * iterate stay stable.
   *
   * The application-layer reuse / reject decision for a case-collision peer
   * lives in `ensureExternalEntry` (`fs.realpath` resolves whether the two
   * case-different paths are the same FS entity); see
   * `file-manager-architecture.md §1.2 Duplicate-entry detection on insert`.
   *
   * Un-parseable rows are skipped with a warning (see `rowToFileEntrySafe`).
   */
  findCaseInsensitivePeers(canonicalPath: CanonicalFilePath): FileEntry[]

  /** Active internal entries whose persisted hash exactly matches, oldest first. */
  findInternalByContentHash(contentHash: ContentHash): FileEntry[]

  /** Number of internal rows awaiting content-hash backfill, including trashed rows. */
  countInternalMissingContentHash(): number

  /** Keyset page of internal rows awaiting content-hash backfill, including trashed rows. */
  findInternalMissingContentHash(afterId: FileEntryId | null, limit: number): InternalFileEntry[]

  /** Mark bytes-derived metadata unknown before an internal blob is atomically replaced. */
  beginInternalContentCommit(id: FileEntryId, commitAt: number): InternalContentCommitSnapshot

  /** Persist metadata derived from the exact bytes committed by a foreground writer. */
  completeInternalContentCommit(id: FileEntryId, metadata: { size: number; contentHash: ContentHash }): boolean

  /** Restore the pre-write metadata when the filesystem commit did not land. */
  restoreInternalContentAfterFailedCommit(id: FileEntryId, snapshot: InternalContentCommitSnapshot): boolean

  /** Repair unknown bytes-derived metadata without changing user-visible timestamps. */
  repairInternalContentMetadataIfUnknown(id: FileEntryId, metadata: { size: number; contentHash: ContentHash }): boolean

  /**
   * Flat listing. Trashed filter defaults to "active only" when `inTrash` is omitted.
   * Un-parseable rows are skipped with a warning (see `rowToFileEntrySafe`).
   */
  findMany(query?: FindEntriesQuery): FileEntry[]

  /** Tx-scoped variant of `findMany` for composing write flows. */
  findManyTx(tx: DbOrTx, query?: FindEntriesQuery): FileEntry[]

  /**
   * Cursor-and-count list backing `GET /files/entries`. Returns
   * `{ items, total, nextCursor }` matching the DataApi cursor response shape,
   * running the page select and the total count as two sequential synchronous queries.
   *
   * Defaults: `limit = 50`, `sortBy = 'createdAt'`, `sortOrder = 'asc'`.
   * Trashed filter defaults to "active only" when `inTrash` is omitted, matching
   * `findMany`.
   *
   * `sortBy: 'size'` is only meaningful within an `origin='internal'` filter
   * (external rows have `size IS NULL`); see the schema-level JSDoc for the
   * mixed-origin caveat.
   *
   * Un-parseable rows are skipped with a warning (see `rowToFileEntrySafe`).
   * `total` is a SQL count and may exceed `items.length` when corrupted
   * rows were skipped.
   */
  listCursor(query?: ListCursorQuery): FileEntryListResponse

  /**
   * Pure-SQL aggregate counts backing the file sidebar. Counts active rows by
   * extension and active external rows by dirname, plus active/trash totals.
   */
  getStats(): FileEntryStats

  /**
   * Active (non-trashed) **manual-policy** entries with zero persistent
   * association rows pointing at them — the DB orphan report's data source.
   * `delete_when_unreferenced` entries are deliberately excluded: they are
   * owned by the cleanup pass (`findCleanupCandidates`), so reporting them
   * here too would double-count auto entries still pending reclamation
   * (young, or beyond the per-pass batch) as manual orphans.
   *
   * Un-parseable rows are skipped with a warning (see `rowToFileEntrySafe`).
   */
  findManualUnreferenced(query?: { origin?: FileEntryOrigin }): FileEntry[]

  /** Auto-policy entries past grace with zero persistent refs (trashed included) — backs the GC pass. */
  findCleanupCandidates(opts: { graceMs: number; limit: number }): FileEntry[]

  /**
   * All entry ids regardless of trashed state — backs the FS orphan sweep,
   * which needs to know which on-disk UUID files have a DB row
   * (active or trashed; both are out of scope for unlink).
   */
  listAllIds(): Set<FileEntryId>

  /** Insert a new row. Violates `fe_origin_consistency` / `fe_size_internal_only` → throws. */
  create(values: CreateFileEntryRow): FileEntry

  /** Tx-scoped variant of `create` for composing write flows. */
  createTx(tx: DbOrTx, values: CreateFileEntryRow): FileEntry

  /** Update mutable columns. Returns the refreshed row. Throws if not found. */
  update(id: FileEntryId, values: UpdateFileEntryRow): FileEntry

  /** Tx-scoped variant of `update` for composing write flows. */
  updateTx(tx: DbOrTx, id: FileEntryId, values: UpdateFileEntryRow): FileEntry

  /**
   * Atomically rewrite both `externalPath` and `name` for an external entry.
   * The rename flow is the **only** sanctioned mutation site for `externalPath`;
   * doing it as a single statement keeps the (path, name) pair consistent under
   * partial-failure scenarios (transient lock, schema constraint).
   */
  setExternalPathAndName(id: FileEntryId, externalPath: CanonicalFilePath, name: string): FileEntry

  /** Tx-scoped variant of `setExternalPathAndName` for composing write flows. */
  setExternalPathAndNameTx(tx: DbOrTx, id: FileEntryId, externalPath: CanonicalFilePath, name: string): FileEntry

  /** Remove the row (CASCADE drops dependent persistent file refs). No-op if already gone. */
  delete(id: FileEntryId): void

  /** Tx-scoped variant of `delete` for composing write flows. */
  deleteTx(tx: DbOrTx, id: FileEntryId): void
}

type FileEntryRow = typeof fileEntryTable.$inferSelect

/**
 * DB row → branded `FileEntry` BO.
 *
 * The DB row carries every column physically (with `null` for fields that
 * don't apply to the row's origin); the BO is a discriminated union where
 * each variant only declares the fields it actually owns. Dispatch on
 * `row.origin`, build a variant-specific plain object dropping the
 * irrelevant columns, then `FileEntrySchema.parse` rehydrates the brand
 * and validates the invariants. See the `fileEntry.ts` header docstring
 * for the "DB row vs Business Object" boundary.
 *
 * Why not align with the project's `nullsToUndefined + timestampToISO`
 * row→entity helper: those helpers were designed for entity types whose
 * schemas use `undefined` for absence and ISO strings for timestamps —
 * FileEntry uses field absence (`origin`-driven) for absence and `number`
 * ms-epoch for timestamps, so the helpers' translations would actively
 * misshape the row. The dispatch-then-parse pattern here is the
 * discriminated-union counterpart and is documented in
 * `docs/references/data/data-api-in-main.md` (§"When `nullsToUndefined +
 * spread` is NOT a fit") as an accepted alternative.
 */
function rowToFileEntry(row: FileEntryRow): FileEntry {
  if (row.origin === 'internal') {
    return FileEntrySchema.parse({
      id: row.id,
      origin: 'internal',
      name: row.name,
      ext: row.ext,
      cleanupPolicy: row.cleanupPolicy,
      size: row.size,
      contentHash: row.contentHash,
      // deletedAt is `optional` on the BO — present iff the DB column is
      // non-null. Bypass `nullsToUndefined` so we don't pull in a helper
      // whose project-wide meaning is "every null becomes undefined";
      // here only this specific column flips.
      ...(row.deletedAt !== null ? { deletedAt: row.deletedAt } : {}),
      createdAt: row.createdAt,
      updatedAt: row.updatedAt
    })
  }
  return FileEntrySchema.parse({
    id: row.id,
    origin: 'external',
    name: row.name,
    ext: row.ext,
    cleanupPolicy: row.cleanupPolicy,
    externalPath: row.externalPath,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt
  })
}

/**
 * Fault-isolating variant of `rowToFileEntry` for BULK reads only.
 *
 * One legacy-corrupted row must not take down a whole collection query —
 * and with it `danglingCache.initFromDb` → `FileManager.onInit` → the
 * entire File IPC surface for the session (#15733). Point reads
 * (`findById` / `getById` / `findByExternalPath`) and write-read-backs
 * (`create` / `update` / `setExternalPathAndName`) deliberately keep
 * throwing: there the caller named a specific row or just validated the
 * payload pre-write, so a silent null would mask a real bug.
 *
 * Contract change for bulk reads: they return every PARSEABLE row, not
 * every physically existing row. Excluded rows are warned with their id.
 *
 * Only validation failures (`ZodError`) are isolated — anything else
 * rethrows, so a programming error inside `rowToFileEntry` cannot
 * masquerade as a corrupt row and vanish from bulk reads.
 */
function rowToFileEntrySafe(row: FileEntryRow): FileEntry | null {
  try {
    return rowToFileEntry(row)
  } catch (error) {
    if (!(error instanceof ZodError)) throw error
    logger.warn('Skipping un-parseable file_entry row in bulk read', {
      id: row.id,
      issues: error.issues
    })
    return null
  }
}

type ListSortBy = NonNullable<ListCursorQuery['sortBy']>
type ListSortOrder = NonNullable<ListCursorQuery['sortOrder']>
const DEFAULT_LIST_SORT_BY: ListSortBy = 'createdAt'
const DEFAULT_LIST_SORT_ORDER: ListSortOrder = 'asc'
const FILE_ENTRY_SIZE_NULL_SORT_VALUE = -1
// SafeExtSchema rejects whitespace, so this non-empty cursor key is reserved for NULL ext and sorts before real ext values.
const FILE_ENTRY_EXT_NULL_SORT_VALUE = ' '
const FILE_EXTENSIONS_BY_TYPE = new Map<FileType, string[]>()
for (const [extension, fileType] of Object.entries(fileTypeMap)) {
  const extensions = FILE_EXTENSIONS_BY_TYPE.get(fileType) ?? []
  extensions.push(extension)
  FILE_EXTENSIONS_BY_TYPE.set(fileType, extensions)
}
const KNOWN_FILE_EXTENSIONS = Object.keys(fileTypeMap)

function getFileTypeFilterCondition(fileType: FileType): SQL {
  const normalizedExtension = sql<string>`lower(${fileEntryTable.ext})`
  if (fileType === 'other') {
    return or(isNull(fileEntryTable.ext), notInArray(normalizedExtension, KNOWN_FILE_EXTENSIONS))!
  }
  return inArray(normalizedExtension, FILE_EXTENSIONS_BY_TYPE.get(fileType) ?? [])
}

function getListSortValue(row: FileEntryRow, sortBy: ListSortBy): string | number {
  switch (sortBy) {
    case 'name':
      return row.name
    case 'updatedAt':
      return row.updatedAt
    case 'size':
      return row.size ?? FILE_ENTRY_SIZE_NULL_SORT_VALUE
    case 'ext':
      return row.ext ?? FILE_ENTRY_EXT_NULL_SORT_VALUE
    case 'createdAt':
      return row.createdAt
  }
}

function getListSortExpression(sortBy: ListSortBy): SQLWrapper {
  switch (sortBy) {
    case 'name':
      return sql<string>`${fileEntryTable.name}`
    case 'updatedAt':
      return sql<number>`${fileEntryTable.updatedAt}`
    case 'size':
      return sql<number>`coalesce(${fileEntryTable.size}, ${FILE_ENTRY_SIZE_NULL_SORT_VALUE})`
    case 'ext':
      return sql<string>`coalesce(${fileEntryTable.ext}, ${FILE_ENTRY_EXT_NULL_SORT_VALUE})`
    case 'createdAt':
      return sql<number>`${fileEntryTable.createdAt}`
  }
}

function getListCursorParser(sortBy: ListSortBy): (raw: string) => string | number | null {
  return sortBy === 'name' || sortBy === 'ext' ? asStringKey : asNumericKey
}

class FileEntryServiceImpl implements FileEntryService {
  private getDbService() {
    return application.get('DbService')
  }

  private getDb() {
    return this.getDbService().getDb()
  }

  withWriteTx<T>(fn: (tx: DbOrTx) => T): T {
    return this.getDbService().withWriteTx(fn)
  }

  findById(id: FileEntryId): FileEntry | null {
    return this.findByIdTx(this.getDb(), id)
  }

  findByIdTx(tx: DbOrTx, id: FileEntryId): FileEntry | null {
    const rows = tx.select().from(fileEntryTable).where(eq(fileEntryTable.id, id)).limit(1).all()
    return rows.length === 0 ? null : rowToFileEntry(rows[0])
  }

  getById(id: FileEntryId): FileEntry {
    return this.getByIdTx(this.getDb(), id)
  }

  getByIdTx(tx: DbOrTx, id: FileEntryId): FileEntry {
    const entry = this.findByIdTx(tx, id)
    if (!entry) {
      throw DataApiErrorFactory.notFound('FileEntry', id)
    }
    return entry
  }

  findByExternalPath(canonicalPath: CanonicalFilePath): FileEntry | null {
    const rows = this.getDb()
      .select()
      .from(fileEntryTable)
      .where(eq(fileEntryTable.externalPath, canonicalPath))
      .limit(1)
      .all()
    return rows.length === 0 ? null : rowToFileEntry(rows[0])
  }

  findCaseInsensitivePeers(canonicalPath: CanonicalFilePath): FileEntry[] {
    const rows = this.getDb()
      .select()
      .from(fileEntryTable)
      .where(
        and(
          isNotNull(fileEntryTable.externalPath),
          sql`lower(${fileEntryTable.externalPath}) = lower(${canonicalPath})`
        )
      )
      // Deterministic ordering for the duplicate-suspect warn log so the
      // first row in the list is stable across runs (helpful for snapshot
      // tests and for the surviving-row selection in any future FileMigrator
      // dedupe pass).
      .orderBy(asc(fileEntryTable.createdAt), asc(fileEntryTable.id))
      .all()
    return rows.map(rowToFileEntrySafe).filter((e): e is FileEntry => e !== null)
  }

  findInternalByContentHash(contentHash: ContentHash): FileEntry[] {
    const rows = this.getDb()
      .select()
      .from(fileEntryTable)
      .where(
        and(
          eq(fileEntryTable.origin, 'internal'),
          isNull(fileEntryTable.deletedAt),
          eq(fileEntryTable.contentHash, contentHash)
        )
      )
      .orderBy(asc(fileEntryTable.createdAt), asc(fileEntryTable.id))
      .all()
    return rows.map(rowToFileEntrySafe).filter((entry): entry is FileEntry => entry !== null)
  }

  countInternalMissingContentHash(): number {
    const rows = this.getDb()
      .select({ value: count() })
      .from(fileEntryTable)
      .where(and(eq(fileEntryTable.origin, 'internal'), isNull(fileEntryTable.contentHash)))
      .all()
    return rows[0]?.value ?? 0
  }

  findInternalMissingContentHash(afterId: FileEntryId | null, limit: number): InternalFileEntry[] {
    const conditions: SQL[] = [eq(fileEntryTable.origin, 'internal'), isNull(fileEntryTable.contentHash)]
    if (afterId !== null) conditions.push(gt(fileEntryTable.id, afterId))
    const rows = this.getDb()
      .select()
      .from(fileEntryTable)
      .where(and(...conditions))
      .orderBy(asc(fileEntryTable.id))
      .limit(limit)
      .all()
    return rows.map((row) => {
      const entry = rowToFileEntry(row)
      if (entry.origin !== 'internal') throw new Error('Expected an internal file entry')
      return entry
    })
  }

  beginInternalContentCommit(id: FileEntryId, commitAt: number): InternalContentCommitSnapshot {
    return application.get('DbService').withWriteTx((tx) => {
      const row = tx
        .select({
          size: fileEntryTable.size,
          contentHash: fileEntryTable.contentHash,
          updatedAt: fileEntryTable.updatedAt
        })
        .from(fileEntryTable)
        .where(and(eq(fileEntryTable.id, id), eq(fileEntryTable.origin, 'internal')))
        .get()
      if (!row || row.size === null) {
        throw DataApiErrorFactory.notFound('InternalFileEntry', id)
      }
      tx.update(fileEntryTable)
        .set({ contentHash: null, updatedAt: commitAt })
        .where(and(eq(fileEntryTable.id, id), eq(fileEntryTable.origin, 'internal')))
        .run()
      return {
        size: row.size,
        contentHash: row.contentHash === null ? null : ContentHashSchema.parse(row.contentHash),
        updatedAt: row.updatedAt,
        commitAt
      }
    })
  }

  completeInternalContentCommit(id: FileEntryId, metadata: { size: number; contentHash: ContentHash }): boolean {
    const size = InternalEntrySchema.shape.size.parse(metadata.size)
    const contentHash = ContentHashSchema.parse(metadata.contentHash)
    const rows = this.getDb()
      .update(fileEntryTable)
      .set({
        size,
        contentHash,
        updatedAt: sql`${fileEntryTable.updatedAt}`
      })
      .where(and(eq(fileEntryTable.id, id), eq(fileEntryTable.origin, 'internal'), isNull(fileEntryTable.contentHash)))
      .returning({ id: fileEntryTable.id })
      .all()
    return rows.length > 0
  }

  restoreInternalContentAfterFailedCommit(id: FileEntryId, snapshot: InternalContentCommitSnapshot): boolean {
    const rows = this.getDb()
      .update(fileEntryTable)
      .set({
        size: snapshot.size,
        contentHash: snapshot.contentHash,
        updatedAt: sql`CASE WHEN ${fileEntryTable.updatedAt} = ${snapshot.commitAt}
          THEN ${snapshot.updatedAt}
          ELSE ${fileEntryTable.updatedAt}
        END`
      })
      .where(and(eq(fileEntryTable.id, id), eq(fileEntryTable.origin, 'internal'), isNull(fileEntryTable.contentHash)))
      .returning({ id: fileEntryTable.id })
      .all()
    return rows.length > 0
  }

  repairInternalContentMetadataIfUnknown(
    id: FileEntryId,
    metadata: { size: number; contentHash: ContentHash }
  ): boolean {
    return this.completeInternalContentCommit(id, metadata)
  }

  findMany(query: FindEntriesQuery = {}): FileEntry[] {
    return this.findManyTx(this.getDb(), query)
  }

  findManyTx(tx: DbOrTx, query: FindEntriesQuery = {}): FileEntry[] {
    const conditions: SQL[] = []
    if (query.origin) {
      conditions.push(eq(fileEntryTable.origin, query.origin))
    }
    if (query.inTrash === true) {
      conditions.push(isNotNull(fileEntryTable.deletedAt))
    } else {
      conditions.push(isNull(fileEntryTable.deletedAt))
    }

    let queryBuilder = tx
      .select()
      .from(fileEntryTable)
      .where(and(...conditions))
      .orderBy(asc(fileEntryTable.createdAt))
      .$dynamic()

    if (query.limit !== undefined) {
      queryBuilder = queryBuilder.limit(query.limit)
    }
    if (query.offset !== undefined) {
      queryBuilder = queryBuilder.offset(query.offset)
    }

    const rows = queryBuilder.all()
    return rows.map(rowToFileEntrySafe).filter((e): e is FileEntry => e !== null)
  }

  listCursor(query: ListCursorQuery = {}): FileEntryListResponse {
    const filterConditions: SQL[] = []
    if (query.origin) {
      filterConditions.push(eq(fileEntryTable.origin, query.origin))
    }
    if (query.inTrash === true) {
      filterConditions.push(isNotNull(fileEntryTable.deletedAt))
    } else {
      filterConditions.push(isNull(fileEntryTable.deletedAt))
    }
    if (query.fileType) {
      filterConditions.push(getFileTypeFilterCondition(query.fileType))
    }

    const sortBy = query.sortBy ?? DEFAULT_LIST_SORT_BY
    const sortOrder = query.sortOrder ?? DEFAULT_LIST_SORT_ORDER
    const sortExpression = getListSortExpression(sortBy)
    const ordering = keysetOrdering(sortExpression, fileEntryTable.id, { major: sortOrder, tie: sortOrder })
    const cursor = decodeListCursor(query.cursor, getListCursorParser(sortBy), 'file-entry')
    const conditions = [...filterConditions]
    if (cursor) {
      conditions.push(ordering.where(cursor))
    }

    const pageSize = query.limit ?? 50
    const where = and(...conditions)
    const filterWhere = and(...filterConditions)

    const rows = this.getDb()
      .select()
      .from(fileEntryTable)
      .where(where)
      .orderBy(...ordering.orderBy)
      .limit(pageSize + 1)
      .all()
    const totalRow = this.getDb().select({ value: count() }).from(fileEntryTable).where(filterWhere).all()
    const pageRows = rows.slice(0, pageSize)

    return {
      items: pageRows.map(rowToFileEntrySafe).filter((e): e is FileEntry => e !== null),
      total: totalRow[0]?.value ?? 0,
      nextCursor:
        rows.length > pageSize && pageRows.length > 0
          ? encodeCursor(getListSortValue(pageRows[pageRows.length - 1], sortBy), pageRows[pageRows.length - 1].id)
          : undefined
    }
  }

  getStats(): FileEntryStats {
    const db = this.getDb()
    const activeTotalRows = db
      .select({ count: count() })
      .from(fileEntryTable)
      .where(isNull(fileEntryTable.deletedAt))
      .all()
    const trashTotalRows = db
      .select({ count: count() })
      .from(fileEntryTable)
      .where(isNotNull(fileEntryTable.deletedAt))
      .all()
    const extRows = db
      .select({ ext: fileEntryTable.ext, count: count() })
      .from(fileEntryTable)
      .where(isNull(fileEntryTable.deletedAt))
      .groupBy(fileEntryTable.ext)
      .all()

    return {
      activeTotal: activeTotalRows[0]?.count ?? 0,
      trashTotal: trashTotalRows[0]?.count ?? 0,
      extCounts: extRows.map((row) => ({ ext: row.ext, count: row.count }))
    }
  }

  findManualUnreferenced(query: { origin?: FileEntryOrigin } = {}): FileEntry[] {
    const conditions: SQL[] = [
      isNull(fileEntryTable.deletedAt),
      eq(fileEntryTable.cleanupPolicy, 'manual'),
      ...persistentRefAbsenceConditions()
    ]
    if (query.origin) conditions.push(eq(fileEntryTable.origin, query.origin))
    const rows = this.getDb()
      .select({ entry: fileEntryTable })
      .from(fileEntryTable)
      .where(and(...conditions))
      .orderBy(asc(fileEntryTable.createdAt))
      .all()
    return rows.map((r) => rowToFileEntrySafe(r.entry)).filter((e): e is FileEntry => e !== null)
  }

  findCleanupCandidates(opts: { graceMs: number; limit: number }): FileEntry[] {
    const conditions: SQL[] = [
      // NOTE: no deletedAt filter — trashed auto entries are reclaimed too (spec §5.1)
      eq(fileEntryTable.cleanupPolicy, 'delete_when_unreferenced'),
      lt(fileEntryTable.createdAt, Date.now() - opts.graceMs),
      ...persistentRefAbsenceConditions()
    ]
    const rows = this.getDb()
      .select({ entry: fileEntryTable })
      .from(fileEntryTable)
      .where(and(...conditions))
      .orderBy(asc(fileEntryTable.createdAt))
      .limit(opts.limit)
      .all()
    return rows.map((r) => rowToFileEntrySafe(r.entry)).filter((e): e is FileEntry => e !== null)
  }

  listAllIds(): Set<FileEntryId> {
    const rows = this.getDb().select({ id: fileEntryTable.id }).from(fileEntryTable).all()
    return new Set(rows.map((r) => r.id))
  }

  create(values: CreateFileEntryRow): FileEntry {
    return this.createTx(this.getDb(), values)
  }

  createTx(tx: DbOrTx, values: CreateFileEntryRow): FileEntry {
    const parsed = CreateFileEntryRowSchema.parse(values)
    const now = Date.now()
    const id = parsed.origin === 'internal' ? parsed.id : uuidv7()
    const rows = tx
      .insert(fileEntryTable)
      .values({
        id,
        origin: parsed.origin,
        name: parsed.name,
        ext: parsed.ext,
        cleanupPolicy: parsed.cleanupPolicy,
        size: parsed.origin === 'internal' ? parsed.size : null,
        contentHash: parsed.origin === 'internal' ? (parsed.contentHash ?? null) : null,
        externalPath: parsed.origin === 'external' ? parsed.externalPath : null,
        deletedAt: null,
        createdAt: now,
        updatedAt: now
      })
      .returning()
      .all()
    return rowToFileEntry(rows[0])
  }

  update(id: FileEntryId, values: UpdateFileEntryRow): FileEntry {
    return this.updateTx(this.getDb(), id, values)
  }

  updateTx(tx: DbOrTx, id: FileEntryId, values: UpdateFileEntryRow): FileEntry {
    // Validate user-controlled string columns BEFORE the SQL UPDATE so a
    // rejected value never persists. Without this, a name / ext failing
    // the FileEntry field schemas commits to SQLite first and only fails at
    // `rowToFileEntry`'s schema parse — leaving the row permanently
    // un-parseable.
    if (values.name !== undefined) SafeNameSchema.parse(values.name)
    if (values.ext !== undefined) InternalEntrySchema.shape.ext.parse(values.ext)
    if (values.cleanupPolicy !== undefined) CleanupPolicySchema.parse(values.cleanupPolicy)
    // Enforce the one-way cleanup-policy invariant at the write site
    // (file-entry-cleanup.md §4.2): a runtime `manual` -> `delete_when_unreferenced`
    // transition does not exist. It is load-bearing — removing the volume safety
    // abort (§5.3) was justified *by* it, so nothing downstream would catch a
    // violation: the demoted entry simply becomes a GC candidate and a user
    // library file is deleted. Until now it rested entirely on the single caller
    // (`create.ts`, upgrade-only) staying disciplined. Rejecting here makes it
    // structural, so a future main-side caller cannot demote by accident.
    if (values.cleanupPolicy === 'delete_when_unreferenced') {
      const current = this.findByIdTx(tx, id)
      if (current?.cleanupPolicy === 'manual') {
        throw DataApiErrorFactory.invalidOperation(
          'update FileEntry',
          `cleanupPolicy cannot be demoted from 'manual' to 'delete_when_unreferenced' (${id})`
        )
      }
    }
    const updates: Partial<typeof fileEntryTable.$inferInsert> = {
      updatedAt: Date.now()
    }
    if (values.name !== undefined) updates.name = values.name
    if (values.ext !== undefined) updates.ext = values.ext
    if (values.cleanupPolicy !== undefined) updates.cleanupPolicy = values.cleanupPolicy
    if (values.deletedAt !== undefined) updates.deletedAt = values.deletedAt
    const rows = tx.update(fileEntryTable).set(updates).where(eq(fileEntryTable.id, id)).returning().all()
    if (rows.length === 0) {
      throw DataApiErrorFactory.notFound('FileEntry', id)
    }
    return rowToFileEntry(rows[0])
  }

  /**
   * Atomically rewrite both `externalPath` and `name` for an external entry —
   * the only sanctioned mutation site for `externalPath`. Used by the rename
   * flow so the (path, name) pair stays consistent under failure.
   */
  setExternalPathAndName(id: FileEntryId, externalPath: CanonicalFilePath, name: string): FileEntry {
    return this.setExternalPathAndNameTx(this.getDb(), id, externalPath, name)
  }

  setExternalPathAndNameTx(tx: DbOrTx, id: FileEntryId, externalPath: CanonicalFilePath, name: string): FileEntry {
    // Same pre-SQL validation rationale as `update` above; an unsafe `name`
    // would corrupt the row past `rowToFileEntry` parse. `externalPath` needs
    // no full re-canonicalization here: the `CanonicalFilePath` brand can only
    // be produced by `canonicalizeFilePath()`, so callers already proved
    // canonicalization at construction time. The null-byte check below is
    // cheap defense-in-depth against a forged `as CanonicalFilePath` cast
    // (e.g. from the lint-exempt `watcher/**` / `tree/**` regimes) that would
    // otherwise persist a poison value SQLite happily stores but that later
    // makes the row unreadable once `canonicalizeAbsolutePath` throws on it.
    SafeNameSchema.parse(name)
    if (externalPath.includes('\0')) {
      throw new Error('setExternalPathAndNameTx: externalPath contains a null byte')
    }
    const rows = tx
      .update(fileEntryTable)
      .set({ externalPath, name, updatedAt: Date.now() })
      .where(eq(fileEntryTable.id, id))
      .returning()
      .all()
    if (rows.length === 0) {
      throw DataApiErrorFactory.notFound('FileEntry', id)
    }
    return rowToFileEntry(rows[0])
  }

  delete(id: FileEntryId): void {
    this.deleteTx(this.getDb(), id)
  }

  deleteTx(tx: DbOrTx, id: FileEntryId): void {
    tx.delete(fileEntryTable).where(eq(fileEntryTable.id, id)).run()
  }
}

export const fileEntryService: FileEntryService = new FileEntryServiceImpl()
